services:
  - type: web
    name: spotdraft-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /static/*
        name: Content-Type
        value: application/javascript
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.html
        name: Content-Type
        value: text/html
      - path: /*
        name: Cache-Control
        value: no-cache 