services:
  - type: web
    name: spotdraft-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://spotdraft-w59a.onrender.com 